package com.mito.common.tools

enum class State (private val displayState: String) {

    ALAVA("Álava"),
    ALBACETE("Albacete"),
    ALICANTE("Alicante"),
    ALMERIA("Almería"),
    ASTURIAS("Asturias"),
    AVILA("Ávila"),
    BADAJOZ("Badajoz"),
    BALEARES("Baleares"),
    BARCELONA("Barcelona"),
    BURGOS("Burgos"),
    CACERES("Cáceres"),
    CADIZ("Cádiz"),
    CANTABRIA("Cantabria"),
    CASTELLON("Castellón"),
    CIUDADREAL("Ciudad Real"),
    CORDOBA("Córdoba"),
    CORUNA("Coruña"),
    CUENCA("Cuenca"),
    GERONA("Gerona"),
    GRANADA("Granada"),
    GUADALAJARA("Guadalajara"),
    GUIPUZCOA("Guipúzcoa"),
    HUELVA("Huelva"),
    HUESCA("Huesca"),
    JAEN("Jaén"),
    LEON("León"),
    LERIDA("Lérida"),
    LUGO("Lugo"),
    MADRID("Madrid"),
    MALAGA("Málaga"),
    MURCIA("Murcia"),
    NAVARRA("Navarra"),
    ORENSE("Orense"),
    PALENCIA("Palencia"),
    LASPALMAS("Las Palmas"),
    PONTEVEDRA("Pontevedra"),
    LARIOJA("La Rioja"),
    SALAMANCA("Salamanca"),
    SEGOVIA("Segovia"),
    SEVILLA("Sevilla"),
    SORIA("Soria"),
    TARRAGONA("Tarragona"),
    TENERIFE("Santa Cruz de Tenerife"),
    TERUEL("Teruel"),
    TOLEDO("Toledo"),
    VALENCIA("Valencia"),
    VALLADOLID("Valladolid"),
    VIZCAYA("Vizcaya"),
    ZAMORA("Zamora"),
    ZARAGOZA("Zaragoza"),
    CEUTA("Ceuta"),
    MELILLA("Melilla");

    override fun toString(): String{
        return displayState
    }
}